### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Michigraf** [mikethrussell/EyeXMouse#1]
hello

im michi and have muscular dystrophy and its hard for me to use a mouse. because my goverment wont pay a expensive eyetracker the dev kit would be the best solution. before i will buy it i just want to ask a question.

how accurate is the detection with your tool? can i use it as a mouse replace. for small movements i can still use my mouse. would it be possible, that the eyetracking is disabled while i use the hardware-mouse?

if i could use this it would be a great help for me and others.

greets
michi

**Comment by tofutim** [comment]
Michigraf, in the latest EyeX software (from Tobii) there is a feature called Mouse Warp which allows you to quickly move the mouse using your eye gaze. The accuracy is not great, but it greatly reduces the distance your mouse has to travel.
