### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by doraemonppc** [mikethrussell/EyeXMouse#2]
Hello Mike.
I'm a volunteer in a special education school. I work with disabled kids that have cereblar paralisis etc.
I have a EyeX and try to run your software but seems to crach.
The admin in the tobii forums said that the problem is that the soft its compilend in debug mode. I've installed the Visual Studio, but I don't know how I can confugure this in nodebug mode.
Sorry, but I'm a noob.
Can you helpme or replace the .exe with a redistributable one?
A lot of kids are waiting for a cheap eyetracking sollution to start speaking to others with special programs or use the computer to make easy their life.
A lot of thanks and sorry for my bad english

**Comment by mpcraven** [comment]
Helllo. Thanks for making the code available.
I have a similar request. The executable is asking for these DLLs relating to Visual Studio 201x.
MSVCR120D.dll
MSVCR110.dll
MSVCP110.dll
The first of these is a debug DLL so installing Visual Studio 201x Redistributables from microsoft.com doesn't solve the issue.
It would be really good to have an .exe to try out with the Eye-X.

**Comment by rayliverified** [comment]
Added PR #3 that contains a compiled EXE with all necessary files to run EyeX.

**Comment by rayliverified** [comment]
Good news is that this software still works even though the last update was over 2 years ago.

**Comment by jsneal** [comment]
The EyeXMouse.exe file still gives me this error message when I try to run it:

"The code execution cannot proceed because MSVCR120D.dll was not found. Reinstalling the program may fix this problem."

**Comment by rayliverified** [comment]
Did you try forking my PR and using the compiled files?

**Comment by jsneal** [comment]
No I did not. I'm a github newb, to be honest. I got it to work using your PR using the compiled .exe file. Thanks!

**Comment by rayliverified** [comment]
You're welcome :) Glad that it worked!
