### ISSUE TITLE
OS X

### ISSUE THREAD

**Issue by Juno808** [mikethrussell/EyeXMouse#4]
Hello,

Could EyeXMouse work on Mac OS X?

Thanks.

juno

**Comment by mwturvey** [comment]
Hey Juno,
The code for this project is pretty windows-specific, so it wouldn't run on a mac (unless you were perhaps using parallels, which may work with eyex, but isn't officially supported by Tobii).  I think the bigger issue here is that, last I checked, Tobii hasn't provided any API support for the Mac that would be required to write an application such as eyexmouse.   

https://developer.tobii.com/community/forums/topic/mac-os-support/
